### ISSUE TITLE
Error at `npm run istanbul`

### ISSUE THREAD

**Issue by tomekwi** [1-liners/1-liners#99]
This is what happened to me after a fresh `npm install` (only the relevant part):

```
> 1-liners@0.2.8 istanbul …/1-liners/1-liners
> istanbul cover ./node_modules/mocha/bin/_mocha  -- --report lcov --compilers js:babel/register --ui qunit ./tests

No coverage information was collected, exit without writing coverage information
…/1-liners/1-liners/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/logger.js:37
    throw new Constructor(this._buildMessage(msg));
          ^
ReferenceError: [BABEL] …/1-liners/1-liners/tests/always.js: Unknown option: attachAuxiliaryComment
    at Logger.error (…/1-liners/1-liners/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/logger.js:37:11)
    at File.normalizeOptions (…/1-liners/1-liners/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:154:29)
    at new File (…/1-liners/1-liners/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:133:22)
    at TransformerPipeline.transform (…/1-liners/1-liners/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:96:16)
    at Object.transformFileSync (…/1-liners/1-liners/node_modules/babel/node_modules/babel-core/lib/babel/api/node.js:108:42)
    at compile (…/1-liners/1-liners/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:109:20)
    at Object._fs2.default.readFileSync (…/1-liners/1-liners/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:143:18)
    at Module._extensions.(anonymous function) (…/1-liners/1-liners/node_modules/istanbul/lib/hook.js:103:29)
    at istanbulLoader (…/1-liners/1-liners/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:156:3)
    at Object.require.extensions.(anonymous function) [as .js] (…/1-liners/1-liners/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:173:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at …/1-liners/1-liners/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (…/1-liners/1-liners/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (…/1-liners/1-liners/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (…/1-liners/1-liners/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Object.Module._extensions.(anonymous function) (…/1-liners/1-liners/node_modules/istanbul/lib/hook.js:107:37)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at runFn (…/1-liners/1-liners/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at …/1-liners/1-liners/node_modules/istanbul/lib/command/common/run-with-cover.js:248:17
    at …/1-liners/1-liners/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at …/1-liners/1-liners/node_modules/istanbul/node_modules/async/lib/async.js:251:17
    at done (…/1-liners/1-liners/node_modules/istanbul/node_modules/async/lib/async.js:132:19)
    at …/1-liners/1-liners/node_modules/istanbul/node_modules/async/lib/async.js:32:16
    at …/1-liners/1-liners/node_modules/istanbul/node_modules/async/lib/async.js:248:21
    at LOOP (fs.js:1474:14)
    at process._tickCallback (node.js:355:11)
```

**Comment by tomekwi** [comment]
I need to release a new patch, so for now I’ll disable coverage checks after every test. Is that ok?

**Comment by stoeffel** [comment]
Sure. Just diaable it. I guess that's an issue with coveralls?

**Comment by tomekwi** [comment]
It doesn’t look like it. This error comes up before coveralls kicks in. It rather looks like *babel* was updated and *istanbul* is no longer compatible with this version – or something.

Do you have the same after running a fresh `npm install`?

**Comment by stoeffel** [comment]
I will try later. I will go for a hike in a few:-)

**Comment by stoeffel** [comment]
This is probably solved in https://github.com/babel/babel/issues/1695

**Comment by stoeffel** [comment]
I updated all dev deps. It works on travis and on my machine. Could you check if it works on your machine?

/cc @tomekwi

**Comment by tomekwi** [comment]
No problem. I’ll have a look in the evening/tomorrow – when I’m back home.

**Comment by tomekwi** [comment]
It’s ok now. Sorry, I forgot to check.
